services:
  app:
    image: ghcr.io/johnnylin-a/cert-sync:latest
    # build:
    #   context: .
    restart: unless-stopped
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./config.yaml:/config.yaml:ro
      - ./.ssh:/.ssh:ro
