name: Build Container Image

on:
  push:
    branches: ["master"]
    paths:
      - Dockerfile
      - "*/**/*.go"
  workflow_dispatch:

jobs:
  build-and-push:
    permissions:
      contents: read
      packages: write
    name: Build Container Image for cert-sync
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.sha }}
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build image
        run: |
          # First, lowercase-ify owner
          export owner=${{ github.repository_owner }}
          export owner=${owner,,}
          docker buildx build \
            --platform linux/amd64,linux/arm64,linux/arm/v7 \
            --push \
            -t "ghcr.io/${owner}/cert-sync:latest" \
            .
